config/routes.rb
Rails.application.routes.draw do
  get 'product/search'
  devise_for :users
  root to: 'top#index'
  get "recipes/search"
  resources :donates, only: [:index, :create]
  resources :users, only: :show
  resources :recipes do
    resources :comments, only: :create
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user

  validates :contents, presence: true, length: { maximum: 100 }
end

app/models/cookingtime.rb
class Cookingtime < ApplicationRecord
  has_many :recipes
end

app/models/donate.rb
class Donate < ApplicationRecord
  attr_accessor :token
  belongs_to :user
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 500, less_than_or_equal_to: 9_999_999, message: 'Out of setting range' },
                    format: { with: /\A[0-9]+\z/, message: 'Half-width number' }

  validates :token, presence: true
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :recipes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :level
  belongs_to :cookingtime
  belongs_to :user
  has_many   :comments, dependent: :destroy
  has_one_attached :image
  has_many   :likes, dependent: :destroy
  has_many   :liked_users, through: :likes, source: :user

  validates :image, presence: true
  validates :explains, presence: true, length: { maximum: 1000 }
  validates :recipes_name, presence: true, length: { maximum: 40 }
  validates :level_id, presence: true
  validates :cookingtime_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :donates
  has_many :comments
  has_many   :likes, dependent: :destroy
  has_many   :liked_recipes, through: :likes, source: :recipe

  validates :email, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i },
                       length: { minimum: 6 }

  validates :nickname, presence: true

  validates :birth, presence: true

  def already_liked?(recipe)
    likes.exists?(recipe_id: recipe.id)
  end
end

app/controllers/donates_controller.rb
class DonatesController < ApplicationController
  def index
    @donate = Donate.new
  end

  def create
    @donate = Donate.new(donate_params)
    if @donate.valid?
      pay_donate
      @donate.save
      redirect_to root_path
    else
      render 'index'
    end
  end

  private

  def pay_donate
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    Payjp::Charge.create(
      amount: donate_params[:price],  # 値段
      card: donate_params[:token],    # カードトークン
      currency: 'jpy'                 # 通貨の種類(日本円)
    )
  end

  def donate_params
    params.require(:donate).permit(:price).merge(token: params[:token], user_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :recipe_params

  def create
    @like = current_user.likes.create(recipe_id: params[:id])
  end

  def destroy
    Like.find_by(recipe_id: params[:id], user_id: current_user.id).destroy
  end

  private

  def recipe_params
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  require 'rakuten_web_service'

  def search
    if params[:keyword].present?
      @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
    else
      render :search
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!,  only: [:new, :show]
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :search_recipe, only: [:index, :search]

  def index
    @recipes = Recipe.all.order('created_at DESC')
    set_level_column
    set_cookingtime_column
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
    render :show if @recipe.user != current_user
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path
    else
      render :edit
    end
  end

  def destroy
    if @recipe.destroy
      redirect_to recipes_path
    else
      render :show
    end
  end

  def show
    @comment = Comment.new
    @comments = @recipe.comments.includes(:user)
    @like = Like.new
  end

  def search
    @results = @r.result.includes(:level).order('created_at DESC')
    @results = @r.result.includes(:cookingtime).order('created_at DESC')
  end

  private

  def recipe_params
    params.require(:recipe).permit(
      :image, :recipes_name, :explains,
      :level_id, :cookingtime_id
    ).merge(user_id: current_user.id)
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def search_recipe
    @r = Recipe.ransack(params[:q])  # 検索オブジェクトを生成
  end

  def set_level_column
    @level_name = Level.select('name').distinct
  end

  def set_cookingtime_column
    @cookingtime_name = Cookingtime.select('name').distinct
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donates_helper.rb
module DonatesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/product/_product_list.erb
<% if @items.present? %>
  <% @items.first(10).each do |item| %>
  <div class= "item-container">
    <div class= "item-image">
      <img src="<%= item['smallImageUrls'][0] %>"></td>
    </div>

    <div class="item-name">
      <a href="<%= item['itemUrl']%>" target="_blank"><%= item['itemName']%></a>
    </div>

    <div class="item-price">
    <%= item['itemPrice'] %>円
    </div>
  </div>
  <% end %>
<% end %>

app/views/product/search.html.erb
<%= render "shared/header"%> 

<div class="search-main">
  <div class= "product-container">
    <div class= 'title'>
      <h1 class="common-sub-title">Search Your Products!</h1>
    </div>

    <div class= 'subtitle'>
    <h2 class="product-subtitle-explain">Vegan製品を検索してみよう！</h2>
    </div>

    <div class="search-box">
    <%= form_with url:product_search_path, method: :get, local: true do |f| %>
      <%= f.text_field :keyword, placeholder: "ヴィーガン", autocomplete: 'off' %>
      <%= f.submit "検索" , :name => nil%>
    <% end %>
    </div>

    <div class= 'subtitle'>
      <h2 class="product-subtitle-explain">検索結果</h2>
    </div>

    <div class= "products-list">
      <%= render partial: 'product_list' %>
    </div>

  </div>
</div>

app/views/top/index.html.erb
<%= render "shared/header" %>

<div class="top-main">

  <div class= "main-header">
    <ul>
      <li><%= link_to 'Recipes',  recipes_path, class: "lists" %></li> 
      <li><%= link_to 'Donation', donates_path, class: "lists" %></li> 
      <li><%= link_to 'Products', product_search_path, class: "lists" %></li> 
    </ul>
  </div>

  <div class= "main-container">
    <div class= "top-img-container">
    <%= image_tag 'top0.png', class: 'top-img' %>
    </div>

    <div class= "second-container">
      <div class= "second-container-right">
        <%= image_tag 'top2.jpeg', class: 'second-img'%>
      </div>
      <div class= "second-container-left">
        <h4 class="vegan-explain-logo">What's Vegan?</h4>
        <h1 class="vegan-explain">定義 ビーガンは魚介類や肉類、卵や乳製品など動物由来のものを<br>
        一切とらない絶対菜食主義者のことです。ベジタリアンと混同される事がありますが、<br>
        卵や乳製品を食べるのに対し、ビーガンは、それらも一切口にしません。<br>
        人によっては食品だけではなく服やシャンプーなどの生活用品も使用しません。<br>
        </h1>
        <br>
        <h4 class="vegan-explain-logo">What's Vegan Beginner?</h4>
        <h1 class="vegan-explain">レシピ投稿機能を使って、ヴィーガンレシピをシェアしましょう！<br>
        検索機能を使ってお気に入りのレシピを見つけたら、<br>
        いいねを押してマイページから簡単に管理。<br>
        その他商品検索機能で欲しい商品を検索したり、<br>
        寄付をしてヴィーガンライフを支持することもできます。<br>
        </h1>
        <br>
        <h4 class="vegan-explain-logo">How Can I Start?</h4>
        <h1 class="vegan-explain">まずは[Recipe]ページからレシピを見てみましょう！<br>
        もしお気に入りのレシピを見つけたら新規登録画面からサインアップをした後<br>
        マイページが作成され、レシピを管理することができます。<br>
        レシピの投稿は、[Recipe]のレシピ一覧右下の[Share]ボタンから投稿できます<br>
        [Donation]ページから、ヴィーガンライフを支持することもできますし、<br>
        [Products]ページからいつでも商品を検索！<br>
        </h1>
      </div>
    </div>  

  </div>

</div>




<%= render "shared/footer" %>