config/routes.rb
Rails.application.routes.draw do
  get 'product/search'
  devise_for :users
  root to: 'top#index'
  get "recipes/search"
  resources :donates, only: [:index, :create]
  resources :users, only: :show
  resources :recipes do
    resources :comments, only: :create
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user

  validates :contents, presence: true, length: { maximum: 100 }
end

app/models/cookingtime.rb
class Cookingtime < ApplicationRecord
  has_many :recipes
end

app/models/donate.rb
class Donate < ApplicationRecord
  attr_accessor :token
  belongs_to :user
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 500, less_than_or_equal_to: 9_999_999, message: 'Out of setting range' },
                    format: { with: /\A[0-9]+\z/, message: 'Half-width number' }

  validates :token, presence: true
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :recipes
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :level
  belongs_to :cookingtime
  belongs_to :user
  has_many   :comments, dependent: :destroy
  has_one_attached :image
  has_many   :likes, dependent: :destroy
  has_many   :liked_users, through: :likes, source: :user

  validates :image, presence: true
  validates :explains, presence: true, length: { maximum: 1000 }
  validates :recipes_name, presence: true, length: { maximum: 40 }
  validates :level_id, presence: true
  validates :cookingtime_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  has_many :donates
  has_many :comments
  has_many   :likes, dependent: :destroy
  has_many   :liked_recipes, through: :likes, source: :recipe

  validates :email, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i },
                       length: { minimum: 6 }

  validates :nickname, presence: true

  validates :birth, presence: true

  def already_liked?(recipe)
    likes.exists?(recipe_id: recipe.id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to recipe_path(@comment.recipe.id)
    else
      @comments = @recipe.comments.includes(:user)
      render 'recipes/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:contents).merge(user_id: current_user.id, recipe_id: params[:recipe_id])
  end
end

app/controllers/donates_controller.rb
class DonatesController < ApplicationController
  def index
    @donate = Donate.new
  end

  def create
    @donate = Donate.new(donate_params)
    if @donate.valid?
      pay_donate
      @donate.save
      redirect_to root_path
    else
      render 'index'
    end
  end

  private

  def pay_donate
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    Payjp::Charge.create(
      amount: donate_params[:price],  # 値段
      card: donate_params[:token],    # カードトークン
      currency: 'jpy'                 # 通貨の種類(日本円)
    )
  end

  def donate_params
    params.require(:donate).permit(:price).merge(token: params[:token], user_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :recipe_params

  def create
    @like = current_user.likes.create(recipe_id: params[:id])
  end

  def destroy
    Like.find_by(recipe_id: params[:id], user_id: current_user.id).destroy
  end

  private

  def recipe_params
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  require 'rakuten_web_service'

  def search
    if params[:keyword].present?
      @items = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
    else
      render :search
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!,  only: [:new, :show]
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :search_recipe, only: [:index, :search]

  def index
    @recipes = Recipe.all.order('created_at DESC')
    set_level_column
    set_cookingtime_column
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
    render :show if @recipe.user != current_user
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path
    else
      render :edit
    end
  end

  def destroy
    if @recipe.destroy
      redirect_to recipes_path
    else
      render :show
    end
  end

  def show
    @comment = Comment.new
    @comments = @recipe.comments.includes(:user)
    @like = Like.new
  end

  def search
    @results = @r.result.includes(:level).order('created_at DESC')
    @results = @r.result.includes(:cookingtime).order('created_at DESC')
  end

  private

  def recipe_params
    params.require(:recipe).permit(
      :image, :recipes_name, :explains,
      :level_id, :cookingtime_id
    ).merge(user_id: current_user.id)
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def search_recipe
    @r = Recipe.ransack(params[:q])  # 検索オブジェクトを生成
  end

  def set_level_column
    @level_name = Level.select('name').distinct
  end

  def set_cookingtime_column
    @cookingtime_name = Cookingtime.select('name').distinct
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donates_helper.rb
module DonatesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/donates/index.html.erb
<%= render "shared/header" %> 
 <%= render 'shared/error_messages', model: @donate %>

<div class= "donation-container">
  <div class= 'title'>
    <h1 class="common-sub-title">Donation</h1>
  </div>

  <div class="donation-info">

    <div class="donate">
      <%= image_tag 'donation-pic.jpeg', class: 'donation-pic' %>
      <h2 class="donation-explain">VeganBeginnerへの活動を支援くださいませ。</h2>
      <p class='donation-sub-explain'>ヴィーガンを多くの人に知ってもらう広告費として大切に使われます。</p>
    </div>

  </div>

  <%= form_with  model: @donate, id: 'charge-form', class: 'card-form',local: true do |f| %>

  <div class='form-donate-wrap'>
    <div><%= f.label :price, "金額" %></div>
    <div><%= f.text_field :price, class:"price", placeholder:"¥500以上" %></div>
  </div>
  
  <div class='form-donate-wrap'>
    <div><%= f.label :number,  "カード番号" %></div>
    <div><%= f.text_field :number, class:"number", placeholder:"カード番号(半角)", maxlength:"16" %></div>
  </div>
  
  <div class='form-donate-wrap'>
    <div><%= f.label :cvc ,"ＣＶＣ" %></div>
    <div><%= f.text_field :cvc, class:"cvc", placeholder:"4桁もしくは3桁の番号", maxlength:"4" %></div>
  </div>
  
  <div class='form-donate-wrap'>
    <p>有効期限</p>
    <div class='input-expiration-date-wrap'>
      <%= f.text_field :exp_month, class:"exp_month", placeholder:"例)3" %>月
      <%= f.text_field :exp_year, class:"exp_year", placeholder:"例)24" %>年
    </div>
  </div>

  <div class='form-donate-wrap'>
    <%= f.submit "支援する" ,class:"button" %>
  </div>
  <% end %>

</div>

app/views/likes/create.js.erb
document.getElementById('recipe_<%= @recipe.id %>').innerHTML = '<%= escape_javascript(render @recipe) %>'

app/views/likes/destroy.js.erb
document.getElementById('recipe_<%= @recipe.id %>').innerHTML = '<%= escape_javascript(render @recipe) %>'

app/views/recipes/_recipe.html.erb
    <% if current_user.already_liked?(recipe) %>
      <%= link_to 'お気に入り解除', destroy_like_path(recipe.id), method: :delete,remote: true %>
    <% else %>
      <%= link_to 'お気に入り追加', create_like_path(recipe.id), method: :post, remote: true %>
    <% end %>

app/views/recipes/edit.html.erb
<%= render "shared/header" %>
<div class='recipe-post'>

<div class= 'post-header'>

  <div class= 'title'>
    <h1 class="common-sub-title">Let's Share Your Vegan Recipes!</h1>
  </div>
  <div class= 'subtitle'>
    <p>訂正箇所を入力してから、[内容を変更する]を押してください。</p>
  </div>

  <%= form_with model: @recipe, local: true do |f| %>

  <div class="new-recipes">

    <div class="recipe-image">
      <h2>Recipe Picture</h2>
      <div class="click-upload">
        <%= f.file_field :image, id:"recipe-image"%>
      </div>
    </div>

    <div class="recipe-name">
      <h2>Recipe Name</h2>
      <%= f.text_area :recipes_name, class:"recipes-text", id:"recipe-name", placeholder:"レシピ名（必須 40文字まで)", maxlength:"40" %>
    </div>

    <div class="recipe-explain">
      <h2>How To Cook</h2>
      <%= f.text_area :explains, class:"recipe-explain-text", id:"recipe-info", placeholder:"レシピの材料・作り方を記述してください（必須 1000文字まで)" ,rows:"7" ,maxlength:"1000" %>
    </div>

  </div>

  <div class="selections">
    <div class= "levels">
      <h3>難易度</h3>
      <%= f.collection_select(:level_id, Level.all, :id, :name, {prompt: "選択してください"}, {class:"select-box", id:"recipe-level"}) %>
    </div>

    <div class= "cookingtimes">
      <h3>調理時間</h3>
      <%= f.collection_select(:cookingtime_id, Cookingtime.all, :id, :name, {prompt: "選択してください"}, {class:"select-box", id:"reccipe-cookingtime"}) %>
    </div>
  </div>


  <div class="recipe-post-button">
    <div class="posting-btn">
      <%= f.submit "内容を変更する" ,class: "new-btn-text" %>
    </div>

  </div>

</div>

  <% end %>

app/views/recipes/index.html.erb
  <%= render "shared/header"%> 

  <div class='recipe-container'>
    <div class= 'index-header'>
      <div class= 'title'>
        <h1 class="common-sub-title">Recipes</h1>
      </div>
      <div class= "subtitle">
        <h2 class= "recipe-index-subtitle">ビーガンレシピを作ってみよう！レシピをシェアしよう！</h2>
        <p class= "recipe-index-subtitle">レベルと調理時間の検索ができます</p>
      </div>
    </div>


    <%= search_form_for @r, url: recipes_search_path do |f| %>
    <div class= 'search-box'>
      <div class="search-level">
        <%= f.label :level_name_eq, 'レベル：' %>
        <%= f.collection_select :level_name_eq, @level_name, :name, :name, include_blank: '指定なし' %>
      </div>

      <div class="search-cookintime">
        <%= f.label :cookingtime_name_eq, '調理時間：' %>
        <%= f.collection_select :cookingtime_name_eq, @cookingtime_name, :name, :name, include_blank: '指定なし' %>
      </div>

      <div class= "search-btn">
        <%= f.submit '検索' %>
      </div>
    </div> 
    <% end %>
    
    <div class="recipe-link">
      <%= link_to("レシピをシェアする", new_recipe_path, {class: "recipe-link-text"}) %>
    </div>


    <main class="main">
      <div class="innner">
        <div class="r-wrapper">
          <% @recipes.each do |recipe| %>
          <div class= "r-list">
            <%= link_to recipe_path(recipe.id) do %> 
            <%= image_tag recipe.image, class: "recipe-img" %>
            <%end%>
            <div class="r-body">
              <div class='r-name'>
                <h3><%= recipe.recipes_name %></h3>
              </div>
              <div class="r-likes">
                <h3>LIKE: <%= recipe.likes.count %></h3>
              </div>
            </div>
          </div>
          <%end%> 
        </div>
      </div>
    </main>


    <div class= 'index-footer'>
      <div class="btn-text">
        <%= link_to image_tag('share.png' , size: '300x200' ,class: "share-btn"), new_recipe_path %>
      </div>
    </div>
  </div>

app/views/recipes/new.html.erb
<%= render "shared/header"%> 
<div class='recipe-post'>

  <div class= 'post-header'>

    <div class= 'title'>
      <h1 class= "common-sub-title">Let's Share Your Vegan Recipes!</h1>
    </div>
    <div class= 'subtitle'>
      <p>全て入力してから、[投稿する]を押してください。</p>
    </div>

  <%= form_with model: @recipe, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>

  <div class="new-recipes">
    <div class="recipe-image">
      <h2>Recipe Picture</h2>
      <div class="click-upload">
        <%= f.file_field :image, id:"recipe-image"%>
      </div>
    </div>

    <div class="recipe-name">
      <h2>Recipe Name</h2>
      <%= f.text_area :recipes_name, class:"recipes-text", id:"recipe-name", placeholder:"レシピ名（必須 40文字まで)", maxlength:"40" %>
    </div>

    <div class="recipe-explain">
      <h2>How To Cook</h2>
      <%= f.text_area :explains, class:"recipe-explain-text", id:"recipe-info", placeholder:"レシピの材料・作り方を記述してください（必須 1000文字まで)" ,rows:"7" ,maxlength:"1000" %>
    </div>
  </div>

  <div class="selections">
    <div class= "levels">
      <h3>難易度</h3>
      <%= f.collection_select(:level_id, Level.all, :id, :name, {prompt: "選択してください"}, {class:"select-box", id:"recipe-level"}) %>
    </div>
    <div class= "cookingtimes">
      <h3>調理時間</h3>
      <%= f.collection_select(:cookingtime_id, Cookingtime.all, :id, :name, {prompt: "選択してください"}, {class:"select-box", id:"reccipe-cookingtime"}) %>
    </div>
  </div>


  <div class="recipe-post-button">
    <div class="posting-btn">
      <%= f.submit "投稿する" ,class: "new-btn-text" %>
    </div>
  </div>
</div>
<% end %>

app/views/recipes/search.html.erb
<%= render "shared/header"%> 

<div class= 'saerch-main'>
  <div class= 'title'>
    <h1 class="common-sub-title">Results</h1>
  </div>
  <div class="recipes-container">
    <% if @results.length !=0 %>
  <main class="main">
    <div class="innner">
      <div class="r-wrapper">
        <% @results.each do |result| %>
        <div class= "r-list">
          <%= link_to recipe_path(result.id) do %> 
          <%= image_tag result.image, class: "recipe-img" %>
          <%end%>
          <div class="r-body">
            <div class='r-name'>
              <h3><%= result.recipes_name %></h3>
            </div>
          </div>
        </div>
        <%end%> 
      </div>
    </div>
  </main> 
  <% else %>
  <div class='no-result'>
    <h2>該当するレシピはありません。</h2>
    <p>シェアしてみませんか？</p>
    <%= link_to 'Share!', new_recipe_path %>
    <% end %>
  </div> 

  <div class= btn-search>
      <%= link_to 'Back', recipes_path, class: "recipe-back-btn" %>
  </div>

</div>

app/views/recipes/show.html.erb
<%= render "shared/header"%> 
<%= render 'shared/error_messages', model: @comment %>

<div class= "recipe-show">

  <div class="show-main-container">
    
    <div class= "show-main-left">
      <div class= recipe-show-img>
        <%= image_tag @recipe.image, class: 'recipe_img' %>
      </div>
    </div>

    <div class= "show-main-right">
      
      <div class= "recipe-show-name">
        <h1 class="recipe-show-name-font"><%= @recipe.recipes_name%></h1>
      </div>

      <div class= "show-recipe-edit-delete">
          <% if current_user == @recipe.user %>
          <%= link_to '編集/', edit_recipe_path(@recipe.id) , method: :get, class: "recipe-edit-btn" %>
          <%= link_to '削除', recipe_path(@recipe.id), method: :delete, class:'recipe-destroy' , data: { confirm: 'Are you sure?' }%>
          <% end %>
      </div>

      <div class= "recipe-show-nickname">
        <h1><%= @recipe.user.nickname %>さんのレシピです</h1>
      </div>


      <div class= "recipe-show-explain">
        <h1 class="recipe-show-explain-font"><%= safe_join(@recipe.explains.split("\n"),tag(:br)) %></h1>
      </div>


      <div class= "recipe-show-level">
        <h1>Level: <%= @recipe.level.name %></h1>
      </div>

      <div class= "recipe-show-cookingtime">
        <h1>Time: <%= @recipe.cookingtime.name %></h1>
      </div>

      <div class= "like-container">
        <span id="recipe_<%= @recipe.id %>">
          <%= render partial: 'recipe', locals: { recipe: @recipe } %>
        </span>
      </div>

      <div class= btn-show>
        <%= link_to 'Back', recipes_path, class: "recipe-back-btn" %>
      </div>
    </div>
    
  </div>

  <div class="comment-title">
    <h5 class="comment-font">Comment</h5>
  </div>

  <div class= "comment-container">
    <div class="comment-box">
      <% if current_user %>
        <%= form_with model: [@recipe,@comment],url: recipe_comments_path(@recipe.id), method: :post, local: true do |f| %>
        <%= f.text_area :contents, class:"comment-text",placeholder: "コメントを記入してください(100文字まで）" %>
      <div class="comment-warn">
          <h2 class="attension">相手のことを考え丁寧なコメントを心がけましょう。</h2>
          <h2 class="attension">不快な言葉遣いなどは利用制限や退会処分となることがあります。</h2>
      </div>
        <button type="submit" class="comment-btn">
        <% f.submit "submit", class: "comment-btn"%>
          <h6>コメントする</h6>
        </button>
        <% end %>
      <% else %>
        <strong><p class="attension">※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
      <% end %>
    </div>


    <div class="comment-index">
    <h2>＜コメント一覧＞</h2>
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
          <strong><%= comment.user.nickname %>：</strong>
          <%= comment.contents %>
          </p>
        <% end %>
      <% end %>
    </div>

  </div>

</div>

app/views/users/show.html.erb
<%= render "shared/second-header"%> 

<div class= "mypage">
    <h2><%= @user.nickname%>さんのマイページ</h2>
    
    <h4 class= "mypage-subtitle">投稿したレシピ</h4>
    <main class="main">
    <div class="innner">
      <div class="r-wrapper">
        <% @user.recipes.each do |recipe| %>
        <div class= "r-list">
          <%= link_to recipe_path(recipe.id) do %> 
          <%= image_tag recipe.image, class: "recipe-img" %>
          <%end%>
          <div class="r-body">
            <div class='r-name'>
              <h3><%= recipe.recipes_name %></h3>
            </div>
            <div class="r-likes">
              <h3>LIKE: <%= recipe.likes.count %></h3>
            </div>
          </div>
        </div>
        <%end%> 
      </div>
    </div>
  </main>


  <h4 class= "mypage-subtitle">お気に入りレシピ</h4>
    <main class="main">
      <div class="innner">
        <div class="r-wrapper">
          <% @user.liked_recipes.each do |recipe| %>
          <div class= "r-list">
            <%= link_to recipe_path(recipe.id) do %> 
            <%= image_tag recipe.image, class: "recipe-img" %>
            <%end%>
            <div class="r-body">
              <div class='r-name'>
                <h3><%= recipe.recipes_name %></h3>
              </div>
              <div class="r-likes">
                <h3>LIKE: <%= recipe.likes.count %></h3>
              </div>
            </div>
          </div>
          <%end%> 
        </div>
      </div>
    </main>
    
</div>